//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsSuplement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsSuplement()
        {
            this.MsCarts = new HashSet<MsCart>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int SuplementID { get; set; }
        public string SuplementName { get; set; }
        public System.DateTime SuplementExpiryDate { get; set; }
        public int SuplementPrice { get; set; }
        public int SuplementTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsCart> MsCarts { get; set; }
        public virtual MsSuplementType MsSuplementType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
