//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsSuplementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsSuplementType()
        {
            this.MsSuplements = new HashSet<MsSuplement>();
        }
    
        public int SuplementTypeID { get; set; }
        public string SuplementTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsSuplement> MsSuplements { get; set; }
    }
}
